//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DementiaHelper.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DementiaHelper.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened when trying to connect, please check id was entered right (it is case sensitive).
        /// </summary>
        public static string Account_ConnectIdErrorText {
            get {
                return ResourceManager.GetString("Account_ConnectIdErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string Account_ConnectIdErrorTitle {
            get {
                return ResourceManager.GetString("Account_ConnectIdErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long..
        /// </summary>
        public static string Account_InvalidPasswordText {
            get {
                return ResourceManager.GetString("Account_InvalidPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string Account_InvalidPasswordTitle {
            get {
                return ResourceManager.GetString("Account_InvalidPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a role before proceeding..
        /// </summary>
        public static string Account_InvalidRoleText {
            get {
                return ResourceManager.GetString("Account_InvalidRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role.
        /// </summary>
        public static string Account_InvalidRoleTitle {
            get {
                return ResourceManager.GetString("Account_InvalidRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Account_LoginFailText {
            get {
                return ResourceManager.GetString("Account_LoginFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string Account_LoginFailTitle {
            get {
                return ResourceManager.GetString("Account_LoginFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string AccountInformationTitle {
            get {
                return ResourceManager.GetString("AccountInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string AddShoppingItem {
            get {
                return ResourceManager.GetString("AddShoppingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment end time:.
        /// </summary>
        public static string AppointmentEndTime {
            get {
                return ResourceManager.GetString("AppointmentEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment start time:.
        /// </summary>
        public static string AppointmentStartTime {
            get {
                return ResourceManager.GetString("AppointmentStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you would want to close this application.
        /// </summary>
        public static string AreYouSureThatYouWantToCloseThisApplication {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantToCloseThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add new appointments, you need to have choosen the citizen your inspecting.
        /// </summary>
        public static string CalendarAddCaregiverFailureSubjekt {
            get {
                return ResourceManager.GetString("CalendarAddCaregiverFailureSubjekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add new appointments, you need to be connected to a person under care.
        /// </summary>
        public static string CalendarAddRelativeFailureSubjekt {
            get {
                return ResourceManager.GetString("CalendarAddRelativeFailureSubjekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string CalendarLanguage {
            get {
                return ResourceManager.GetString("CalendarLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calender.
        /// </summary>
        public static string CalenderTitle {
            get {
                return ResourceManager.GetString("CalenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det var ikke muligt at forbinde til vores server prøv igen senere.
        /// </summary>
        public static string CanNotConnectToServer {
            get {
                return ResourceManager.GetString("CanNotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No citizen choosen.
        /// </summary>
        public static string CaregiverAddFailureTitle {
            get {
                return ResourceManager.GetString("CaregiverAddFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver.
        /// </summary>
        public static string CaregiverRole {
            get {
                return ResourceManager.GetString("CaregiverRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caretaker Chat.
        /// </summary>
        public static string Chat_ChatTitleCaretaker {
            get {
                return ResourceManager.GetString("Chat_ChatTitleCaretaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen Chat.
        /// </summary>
        public static string Chat_ChatTitleCitizen {
            get {
                return ResourceManager.GetString("Chat_ChatTitleCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Chat.
        /// </summary>
        public static string Chat_ChatTitleRelative {
            get {
                return ResourceManager.GetString("Chat_ChatTitleRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatTitle {
            get {
                return ResourceManager.GetString("ChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Citizen.
        /// </summary>
        public static string ChooseCitizenTitle {
            get {
                return ResourceManager.GetString("ChooseCitizenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choosen citizen is:.
        /// </summary>
        public static string ChoosenCitizen {
            get {
                return ResourceManager.GetString("ChoosenCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen Primary Relative.
        /// </summary>
        public static string ChoosenPrimaryRelative {
            get {
                return ResourceManager.GetString("ChoosenPrimaryRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose primary relative.
        /// </summary>
        public static string ChoosenPrimaryRelativeTitle {
            get {
                return ResourceManager.GetString("ChoosenPrimaryRelativeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Primary Relative.
        /// </summary>
        public static string ChoosePrimaryRelative {
            get {
                return ResourceManager.GetString("ChoosePrimaryRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string CitizenHomeTitle {
            get {
                return ResourceManager.GetString("CitizenHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen id.
        /// </summary>
        public static string CitizenId {
            get {
                return ResourceManager.GetString("CitizenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened when trying to connect, please try again later.
        /// </summary>
        public static string Connection_ErrorText {
            get {
                return ResourceManager.GetString("Connection_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string Connection_ErrorTitle {
            get {
                return ResourceManager.GetString("Connection_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the persons under care ID, given in the account Information view of the person with dementia.
        /// </summary>
        public static string ConnectToCitizenLabelText {
            get {
                return ResourceManager.GetString("ConnectToCitizenLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demented Person Id.
        /// </summary>
        public static string ConnectToCitizenPlaceholderText {
            get {
                return ResourceManager.GetString("ConnectToCitizenPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To  Citizen.
        /// </summary>
        public static string ConnectToCitizenTitle {
            get {
                return ResourceManager.GetString("ConnectToCitizenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregivers nursing home id.
        /// </summary>
        public static string ConnectToNursingHomePlaceholderText {
            get {
                return ResourceManager.GetString("ConnectToNursingHomePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to nursing home.
        /// </summary>
        public static string ConnectToNursingHomeTitle {
            get {
                return ResourceManager.GetString("ConnectToNursingHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactListTitle {
            get {
                return ResourceManager.GetString("ContactListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account as:.
        /// </summary>
        public static string CreateAccountAs {
            get {
                return ResourceManager.GetString("CreateAccountAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new appointment.
        /// </summary>
        public static string CreateNewAppointment {
            get {
                return ResourceManager.GetString("CreateNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DayTitle {
            get {
                return ResourceManager.GetString("DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caretaker.
        /// </summary>
        public static string DementiaRole {
            get {
                return ResourceManager.GetString("DementiaRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of appointment:.
        /// </summary>
        public static string DescriptionOfAppointment {
            get {
                return ResourceManager.GetString("DescriptionOfAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string EditProfileTitle {
            get {
                return ResourceManager.GetString("EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Information.
        /// </summary>
        public static string EditUserInformation {
            get {
                return ResourceManager.GetString("EditUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened when trying to remove item, please try again later.
        /// </summary>
        public static string ErrorOnRemove {
            get {
                return ResourceManager.GetString("ErrorOnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorOnRemoveTitle {
            get {
                return ResourceManager.GetString("ErrorOnRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string General_Back {
            get {
                return ResourceManager.GetString("General_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        public static string General_InvalidEmailText {
            get {
                return ResourceManager.GetString("General_InvalidEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string General_InvalidEmailTitle {
            get {
                return ResourceManager.GetString("General_InvalidEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out each field..
        /// </summary>
        public static string General_NullText {
            get {
                return ResourceManager.GetString("General_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill each field.
        /// </summary>
        public static string General_NullTitle {
            get {
                return ResourceManager.GetString("General_NullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string General_Ok {
            get {
                return ResourceManager.GetString("General_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My pictures.
        /// </summary>
        public static string ImageGalleryTitle {
            get {
                return ResourceManager.GetString("ImageGalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert nursing home id, you can find this in the delievered papers from the nursing home.
        /// </summary>
        public static string InsertCarecenterIdText {
            get {
                return ResourceManager.GetString("InsertCarecenterIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert dementia id, you can find this in the demented persons account information.
        /// </summary>
        public static string InsertDementiaIdText {
            get {
                return ResourceManager.GetString("InsertDementiaIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemToAdd {
            get {
                return ResourceManager.GetString("ItemToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login facebook.
        /// </summary>
        public static string LoginWithFacebook {
            get {
                return ResourceManager.GetString("LoginWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login google.
        /// </summary>
        public static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOutTitle {
            get {
                return ResourceManager.GetString("LogOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthTitle {
            get {
                return ResourceManager.GetString("MonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create appointment.
        /// </summary>
        public static string NewAppointment {
            get {
                return ResourceManager.GetString("NewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New note.
        /// </summary>
        public static string NewNote {
            get {
                return ResourceManager.GetString("NewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next appointment:.
        /// </summary>
        public static string NextAppointment {
            get {
                return ResourceManager.GetString("NextAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note, only shared among a nursing home.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NoteTitle {
            get {
                return ResourceManager.GetString("NoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver center id.
        /// </summary>
        public static string NursingHomeId {
            get {
                return ResourceManager.GetString("NursingHomeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        public static string PersonalDetails {
            get {
                return ResourceManager.GetString("PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connected citizen.
        /// </summary>
        public static string RelativeAddFailureTitle {
            get {
                return ResourceManager.GetString("RelativeAddFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatives.
        /// </summary>
        public static string RelativesRole {
            get {
                return ResourceManager.GetString("RelativesRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search citizen.
        /// </summary>
        public static string SearchCitizen {
            get {
                return ResourceManager.GetString("SearchCitizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contacts.
        /// </summary>
        public static string SearchContacts {
            get {
                return ResourceManager.GetString("SearchContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søg pårørende.
        /// </summary>
        public static string SearchRelative {
            get {
                return ResourceManager.GetString("SearchRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See todays appointments.
        /// </summary>
        public static string SeeListOfTodaysAppointments {
            get {
                return ResourceManager.GetString("SeeListOfTodaysAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See months appointments.
        /// </summary>
        public static string SeeMonthsAppointments {
            get {
                return ResourceManager.GetString("SeeMonthsAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See todays appointments.
        /// </summary>
        public static string SeeTodaysAppointments {
            get {
                return ResourceManager.GetString("SeeTodaysAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See weeks appointments.
        /// </summary>
        public static string SeeWeeksAppointments {
            get {
                return ResourceManager.GetString("SeeWeeksAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping List.
        /// </summary>
        public static string ShoppingList {
            get {
                return ResourceManager.GetString("ShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add new items, you need to have choosen the citizen your inspecting.
        /// </summary>
        public static string ShoppingListAddCaregiverFailureSubjekt {
            get {
                return ResourceManager.GetString("ShoppingListAddCaregiverFailureSubjekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to add new items, you need to be connected to a person under care.
        /// </summary>
        public static string ShoppingListAddRelativeFailureSubjekt {
            get {
                return ResourceManager.GetString("ShoppingListAddRelativeFailureSubjekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item:.
        /// </summary>
        public static string ShoppingListItemDescription {
            get {
                return ResourceManager.GetString("ShoppingListItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string ShoppingListItemQuantity {
            get {
                return ResourceManager.GetString("ShoppingListItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoppinglist.
        /// </summary>
        public static string ShoppingListTitle {
            get {
                return ResourceManager.GetString("ShoppingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string WeekTitle {
            get {
                return ResourceManager.GetString("WeekTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
